# Generated by Django 2.2.6 on 2019-10-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('DNI', models.CharField(default='', max_length=45)),
                ('tipo_DNI', models.CharField(default='', max_length=45)),
                ('ciudad', models.CharField(default='', max_length=10)),
                ('pais', models.IntegerField(default=57)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(default='', max_length=10)),
                ('tipo', models.CharField(default='', max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('contacto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Contacto')),
            ],
            options={
                'db_table': 'telefonos',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(default='', max_length=45)),
                ('tipo', models.CharField(default='', max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('contacto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Contacto')),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=250)),
                ('tipo', models.CharField(default='', max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('contacto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Contacto')),
            ],
            options={
                'db_table': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=45)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion', models.CharField(default='', max_length=250)),
                ('tipo', models.CharField(default='', max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('contactos', models.ManyToManyField(to='db.Contacto')),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
    ]
